# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27fb5e872fe2173d52ba535ffd8f7cb09c229ddca372c05499ae426514388fea9f43b9873c366930af71bf9491de381a1df410437cd428fd6944b1cd8b3f215d

test:
  secret_key_base: 8a91c7f16fcf2f4381884203ddd80d118ae3ad92be689d2d3b114c7b53a96beccae1955f537b1339363466e657cf2528dd3d22a883e83e6b4facae47d8a7b57a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
